name: "Create Azure App Credentials 1.0"

on:
  workflow_dispatch:
    inputs:
      ACTION:
        description: 'Action to perform'
        required: true
        default: 'create'
        type: choice
        options:
          - create
          - delete
      APP_ID:
        description: 'Azure App ID'
        required: true
        default: '00000000-0000-0000-0000-000000000000'
        type: string
      BRANCH_NAME:
        description: 'Github Branch Name'
        required: true
        default: 'feature/branch-name'
        type: string
      OIDC_CREDENTIAL_NAME:
        description: 'OIDC Credential Name'
        required: true
        default: 'dev-dave-1'
        type: string

permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT: ${{ secrets.AZURE_TENANT }}

jobs:
  create_az_app_creds:
    name: 'Create Azure App Credentials'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
            
      - name: 'AZ Login pre apply'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT }}

      
      - name: Add OIDC federation credentials
        if: ${{ github.event.inputs.ACTION == 'create' }}
        run: |
          # Add OIDC federation credentials
          az ad app federated-credential create \
            --id $APP_ID \
            --parameters '{
              "name": "${{ github.event.inputs.OIDC_CREDENTIAL_NAME }}",
              "issuer": "https://token.actions.githubusercontent.com",
              "subject": "repo:defencedigital/ccoe:ref:refs/heads/${{ github.event.inputs.BRANCH_NAME }}",
              "description": "GitHub Actions OIDC - Branch ${{ github.event.inputs.BRANCH_NAME }}",
              "audiences": ["api://AzureADTokenExchange"]
            }'

      - name: Delete OIDC federation credentials
        if: ${{ github.event.inputs.ACTION == 'delete' }}
        run: |
          # Delete OIDC federation credentials
          az ad app federated-credential delete \
            --id $APP_ID \
            --federated-credential-id ${{ github.event.inputs.OIDC_CREDENTIAL_NAME }}
